name: builder-test-history-work



    
on: 
  pull_request:
        branches:
          - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
      
    steps:
     - uses: actions/checkout@v3

      # 2️⃣ Installer Java et Maven
     - name: JDK17 setup
       uses: actions/setup-java@v3
       with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Exécuter les tests Maven
     - run: mvn test
      #- run: npm ci
      #- run: npm test
      #- run: npm run build

